[general]
data_file_name = 'small_med.xlsx'
# Can equal 'Random', 'Employee', 'Degree', 'Pagerank transpose', or 'Pagerank'
attack_type = 'Random'
has_metadata = false
max_tiers = 3
repeats_per_node = 20

[operations]
compare_tiers = false
get_thresholds = true


[parallel]
# Can equal 'auto', 'repeat', 'rho', 'all', or None
tiers_parallel_mode = 'rho'
# Can equal true or false
thresholds_parallel = true


[breakdown_thresholds]
reachable_node_threshold = 500
breakdown_threshold = 0.80
thinning_ratio = 0.005
